# Generated by Django 2.2 on 2019-04-11 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_movrotativo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movrotativo',
            old_name='ckeckin',
            new_name='checkin',
        ),
    ]
