# Generated by Django 2.2 on 2019-04-12 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190412_1521'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MovMensalista',
            new_name='Mensalista',
        ),
    ]
