# Generated by Django 2.2 on 2019-04-12 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_movmensalista'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movmensalista',
            old_name='data_pagameno',
            new_name='data_pagamento',
        ),
    ]
